Making it possible to recursively clean files in sub-directories
pytroll/trollmoves pull request #173
Opened 2023-05-30 10:57 UTC by adybbroe

Refactor the files cleaning a little, and making it possible to recursively clean sub-directories

 - [ ] Closes #xxxx 
 - [ ] Tests added  
 - [ ] Fully documented 
 - [ ] Add your name to `AUTHORS.md` if not there already

2023-06-01 13:39 UTC, adybbroe commented
You can have a look, and see what you think @TAlonglong @pnuu and @mraspaud 
But I felt tempted to refactor a bit further, reducing the number of arguments in the various function calls in `filescleaner.py` and warpping them in a class....

2023-06-05 06:13 UTC, pnuu requested changes
Some change requests inline.

2023-06-05 06:13 UTC, pnuu commented on trollmoves/filescleaner.py
> +    ref_time = datetime.utcnow() - timedelta(**kws)
This should be a separate function, `_get_reference_time()` for example.

2023-06-05 06:13 UTC, pnuu commented on trollmoves/tests/test_filescleaner.py
> +    """Test cleaning a directory for files of a certain age."""
The docstring doesn't match the actual test (nor the test function name).

2023-06-05 06:13 UTC, pnuu commented on trollmoves/tests/test_filescleaner.py
> +    """
```suggestion
    """Test cleaning a directory tree for files which were created before the given time."""
```

2023-06-05 06:13 UTC, pnuu commented on trollmoves/tests/test_filescleaner.py
> +    """
```suggestion
    """Test cleaning a directory tree for files that have not been modified after the given time."""
```

2025-06-13 11:33 UTC, adybbroe commented on trollmoves/filescleaner.py
> +                        LOGGER.debug("Was trying to remove empty directory, but failed. Should not have come here!")
Thanks, done!

2025-06-13 11:36 UTC, adybbroe commented on trollmoves/filescleaner.py
> +                section_size += stat.st_size
Thanks fixed.

2025-06-13 11:37 UTC, adybbroe commented on trollmoves/filescleaner.py
> +        recursive = False
Done, thanks

2025-06-13 11:55 UTC, adybbroe commented on trollmoves/filescleaner.py
> +        recursive = False
Info is a normal dict though

2025-06-13 11:55 UTC, adybbroe commented on trollmoves/filescleaner.py
> +    ref_time = datetime.utcnow() - timedelta(**kws)
Yeah, good, thx.

2025-06-23 06:34 UTC, adybbroe commented
Any chance you will hve time looking at this one @pnuu and/or @mraspaud ?

2025-06-23 07:23 UTC, pnuu approved these changes

2025-06-23 08:09 UTC, merged